spring.application.name=studentcrud

spring.datasource.url=jdbc:postgresql://localhost:5432/studentCRUD
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

server.error.include-message=always
